"""empty message

Revision ID: a0035c4ed126
Revises: dda0b253577e
Create Date: 2020-12-28 16:28:57.062070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0035c4ed126'
down_revision = 'dda0b253577e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('form', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('option', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('option', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('question', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('question', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'meta')
    op.drop_column('question', 'is_archived')
    op.drop_column('option', 'meta')
    op.drop_column('option', 'is_archived')
    op.drop_column('form', 'meta')
    op.drop_column('form', 'is_archived')
    # ### end Alembic commands ###
